version: '2'

services:
  example_service4:
    build: .
    image: example_service4:0.0.1
    volumes:
      - "./flags:/root/flags"
    ports:
      - "4444:4444"
    restart: always
    networks:
      - example_service4

networks:
  example_service4:
    driver: bridge