version: '2'

services:
  example_service3:
    build: .
    image: example_service3:0.0.1
    volumes:
      - "./flags:/root/flags"
    ports:
      - "4443:4443"
    restart: always
    networks:
      - example_service3

networks:
  example_service3:
    driver: bridge